from django.contrib import admin
from .models import *

admin.site.register(Alumni)
admin.site.register(AlumniHas)
admin.site.register(Award)
admin.site.register(Club)
admin.site.register(Course)
admin.site.register(CourseTeaching)
admin.site.register(Degree)
admin.site.register(EntryRequirement)
admin.site.register(EquivalentClass)
admin.site.register(ExtraCurricularProgram)
admin.site.register(ExtracurricularOfferings)
admin.site.register(Faculty)
admin.site.register(FieldOfStudy)
admin.site.register(GruUser)
admin.site.register(Major)
admin.site.register(Preference)
admin.site.register(PreferredUni)
admin.site.register(Professor)
admin.site.register(Provides)
admin.site.register(Ranking)
admin.site.register(Sport)
admin.site.register(Staff)
admin.site.register(University)
# Register your models here.
