# Generated by Django 3.1.7 on 2021-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210407_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='id',
        ),
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
