# Generated by Django 3.1.7 on 2021-04-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210407_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'managed': False},
        ),
    ]
