# Generated by Django 3.1.7 on 2021-04-07 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210407_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularofferings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for extracurricular offerings', primary_key=True, serialize=False),
        ),
    ]
