# Generated by Django 3.1.7 on 2021-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210407_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularofferings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
