# Generated by Django 3.1.7 on 2021-04-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210407_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtracurricularOfferings',
        ),
        migrations.DeleteModel(
            name='AlumniHas',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseTeaching',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='EntryRequirement',
        ),
        migrations.DeleteModel(
            name='EquivalentClass',
        ),
        migrations.DeleteModel(
            name='ExtraCurricularProgram',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='FieldOfStudy',
        ),
        migrations.DeleteModel(
            name='GruUser',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='PreferenceContain',
        ),
        migrations.DeleteModel(
            name='PreferredUni',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Provides',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AlterModelOptions(
            name='alumni',
            options={},
        ),
    ]
