# Generated by Django 3.1.7 on 2021-04-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210407_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='id',
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.UniqueConstraint(fields=('name', 'field'), name='uniqueDegree'),
        ),
    ]
