# Generated by Django 3.1.7 on 2021-04-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210408_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
