# Generated by Django 3.1.7 on 2021-04-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210409_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnihas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseteaching',
            options={},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entryrequirement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equivalentclass',
            options={},
        ),
        migrations.AlterModelOptions(
            name='extracurricularofferings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='extracurricularprogram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gruuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preferencecontain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preferreduni',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='provides',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
    ]
