# Generated by Django 3.1.7 on 2021-04-14 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210414_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='provides',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='extracurricularofferings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='extracurricularprogram',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AlterField(
            model_name='extracurricularofferings',
            name='excurricular_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extracurricularprogram',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preferreduni',
            name='pref_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular preference', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preferreduni',
            name='preferred_uni_name',
            field=models.TextField(default='uni'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
