# Generated by Django 3.1.7 on 2021-04-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210414_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={},
        ),
    ]
