# Generated by Django 3.1.7 on 2021-04-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210414_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'managed': False},
        ),
    ]
