# Generated by Django 3.1.7 on 2021-04-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210414_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pref_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
