# Generated by Django 3.1.7 on 2021-04-14 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210414_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferreduni',
            name='pref_id',
            field=models.AutoField(default=uuid.uuid4, help_text='Unique ID for this particular preference', primary_key=True, serialize=False),
        ),
    ]
